apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169226187
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169226187
    app.kubernetes.io/part-of: test-app-169226187
  name: go-169226187
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169226187
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169226187
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169226187/go-169226187@sha256:9d36151cbb2acf8b708b69f9b6586d313763ee8fb6db12a8d9c9f9b2d805995d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
